//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_Nizamiev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public int CategoryID { get; set; }
        public int PriorityID { get; set; }
        public int DepartmentID { get; set; }
        public int AssignedToEmployeeID { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual User User { get; set; }
        public virtual OrderCategories OrderCategories { get; set; }
        public virtual OrderPriorities OrderPriorities { get; set; }
    }
}
